### PR TITLE
Curmudgeon none value

### PR DESCRIPTION
**Pull request by jmartin-rally**
In some cases, the value for a category is "".  This looks funny, so I made a config setting to allow the user to make the app say "None" instead.

### CODE REVIEW

**Comment by krmorse** [comment]
wow, with a setting field and everything!  thanks for contributing.  i'll try to get this merged and updated in the community app soon...

**Comment by krmorse** [comment]
@jmartin-rally, after thinking about it more: is there ever a reason you wouldn't want it to say none?  i'm leaning towards getting rid of the setting and just having this be the default behavior...

**Comment by jmartin-rally** [comment]
ha ha. I went back and forth on this, too.  Ideally, I'd have made it a setting to let the user specify the label to use.  It is remotely possible that an admin could make an actual value of None, but it seems unlikely.

I'd have really liked to have just changed the label instead of mucking with the hash, but I didn't think it through too strongly to figure out the path for that.

**Comment by krmorse** [comment]
I integrated the spirit of this into this repo and the RallyCommunity fork.  And I added tests!

**Comment by krmorse** [comment]
Some more color: it will render -- No Entry -- for dropdowns, -- No Owner -- for user fields and None for everything else...

**Pull request closed without merging**
